/*
 * File: app/store/ConfigStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Incident.store.ConfigStore', {
    extend: 'Ext.data.Store',
    alias: 'store.configstore',

    requires: [
        'Incident.model.ConfigModel'
    ],

    config: {
        model: 'Incident.model.ConfigModel',
        storeId: 'configstoreid',
        proxy: {
            type: 'ajax',
            url: '/json_dependency_files/config.json',
            reader: {
                type: 'json',
                rootProperty: 'config'
            }
        }
    },

    constructor: function() {
        var me = this;
        me.callParent(arguments);
        me.getProxy().on([{
            fn: 'onAjaxproxyException',
            event: 'exception',
            scope: me
        }]);
    },

    onAjaxproxyException: function(server, response, operation, options) {
        var fn = Incident.app.getController('GlobalControl');
        fn.Var('sett', 'url-prefex', '');
        fn.launch();
    }

});