/*
 * File: app/store/SettingsStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Incident.store.SettingsStore', {
    extend: 'Ext.data.Store',
    alias: 'store.settingsstore',

    requires: [
        'Incident.model.LocalModel'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        model: 'Incident.model.LocalModel',
        storeId: 'settingsstoreid',
        proxy: {
            type: 'sessionstorage',
            id: 'settingsstorageid'
        },
        grouper: {
            groupFn: function(record) {
                if(record.data.localid === 'USERNAME_LOG' && record.data.value === null)
                {
                    return 'Debug';
                }

                if(record.data.localid === 'LANGVALUE')
                {
                    return 'Debug';
                }

                //if nothing yet, becomes a settings
                try
                {
                    return Incident.app.getController('GlobalControl').Var('stat', 'button_settings');
                }
                catch(err)
                {
                    return 'Settings';
                }
            },
            sortProperty: 'DESC'
        }
    }
});