/*
 * File: app/store/TemplateStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Incident.store.TemplateStore', {
    extend: 'Ext.data.Store',
    alias: 'store.templatestore',

    requires: [
        'Incident.model.TemplateModel'
    ],

    config: {
        autoLoad: false,
        model: 'Incident.model.TemplateModel',
        storeId: 'templatestoreid',
        proxy: {
            type: 'ajax',
            url: '/json_dependency_files/template_list.json',
            reader: {
                type: 'json',
                rootProperty: 'templates'
            }
        },
        grouper: {
            groupFn: function(record) {
                var recordgroup = record.data.type;
                if(recordgroup !== undefined)
                return recordgroup;
                else
                return 'Other';
            }
        }
    }
});