/*
 * File: app/view/Homescreen.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Incident.view.Homescreen', {
    extend: 'Ext.Container',
    alias: 'widget.homescreenview',

    config: {
        id: 'homescreenviewid',
        layout: {
            type: 'fit'
        },
        scrollable: false,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'settingsbuttonid2',
                        ui: 'main-button',
                        width: 125,
                        iconAlign: 'right',
                        iconCls: 'settings',
                        iconMask: true,
                        text: 'Settings'
                    }
                ]
            },
            {
                xtype: 'list',
                id: 'homescreenlistid',
                styleHtmlContent: true,
                ui: 'round',
                itemTpl: [
                    '<span style="font-size:20px;">&nbsp;{name}</span><br><i>&nbsp;&nbsp;&nbsp;{description}</i>'
                ],
                store: 'templatestoreid',
                disableSelection: true,
                grouped: true,
                onItemDisclosure: false,
                pinHeaders: false
            }
        ]
    }

});