/*
 * File: app/view/LoginView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Incident.view.LoginView', {
    extend: 'Ext.Container',
    alias: 'widget.loginview',

    requires: [
        'Ext.Img',
        'Ext.form.FieldSet',
        'Ext.field.Password'
    ],

    config: {
        id: 'loginviewid',
        ui: '',
        layout: {
            type: 'card'
        },
        scrollable: false,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'guestbuttonid',
                        ui: 'main-button',
                        width: 125,
                        iconCls: 'user',
                        iconMask: true,
                        text: 'Guest'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'settingsbuttonid',
                        ui: 'main-button',
                        width: 125,
                        iconAlign: 'right',
                        iconCls: 'settings',
                        iconMask: true,
                        text: 'Settings'
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'mainloginviewid',
                ui: '',
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'container',
                        centered: true,
                        width: '100%',
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'container',
                                margin: '0 0 5 0',
                                width: '100%',
                                layout: {
                                    align: 'center',
                                    pack: 'center',
                                    type: 'vbox'
                                },
                                items: [
                                    {
                                        xtype: 'image',
                                        height: 69,
                                        width: 207,
                                        src: 'resources/images/logo.png'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                id: 'loginfieldsetid',
                                maxWidth: 300,
                                width: '100%',
                                layout: {
                                    align: 'start',
                                    type: 'vbox'
                                },
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id: 'usernameid',
                                        itemId: 'username',
                                        width: '100%',
                                        name: 'username',
                                        placeHolder: 'Username'
                                    },
                                    {
                                        xtype: 'passwordfield',
                                        id: 'passwordid',
                                        itemId: 'password',
                                        width: '100%',
                                        name: 'password',
                                        placeHolder: 'Password'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                id: 'loginbuttonid',
                                margin: '-10 0 0 0',
                                maxWidth: 300,
                                ui: 'main-button',
                                width: '90%',
                                text: 'Log In (loading...)'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});