/*
 * File: app/view/Mainview.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Incident.view.Mainview', {
    extend: 'Ext.Container',
    alias: 'widget.mainview',

    config: {
        id: 'mainviewid',
        layout: {
            type: 'card'
        },
        scrollable: false,
        items: [
            {
                xtype: 'tabpanel',
                id: 'maintabsid',
                tabBar: {
                    docked: 'top',
                    id: 'maintabstabbarid',
                    ui: 'maintabsui',
                    layout: {
                        pack: 'center',
                        type: 'hbox'
                    }
                },
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        id: 'maintabstoolbarid',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                id: 'confirmbuttonid',
                                maxWidth: 200,
                                ui: 'main-button',
                                width: '45%',
                                text: 'Confirm'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                id: 'declinebuttonid',
                                maxWidth: 200,
                                ui: 'main-button',
                                width: '45%',
                                text: 'Decline'
                            },
                            {
                                xtype: 'spacer'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});