/*
 * File: app/view/MultiView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Incident.view.MultiView', {
    extend: 'Ext.Container',
    alias: 'widget.multiview',

    requires: [
        'Ext.field.Search',
        'Ext.dataview.List'
    ],

    config: {
        activeItem: 1,
        id: 'multiviewid',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                id: 'multitoolbarid',
                items: [
                    {
                        xtype: 'button',
                        id: 'multibackbuttonid',
                        width: 125,
                        text: 'Back'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'multiokbuttonid',
                        ui: 'confirm',
                        width: 125,
                        text: 'Ok'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                id: 'multisearchbarid',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        cls: [
                            'search-field-clear-size'
                        ],
                        id: 'multisearchfieldid',
                        maxWidth: 600,
                        width: '90%',
                        placeHolder: 'Search...'
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'multimidview',
                scrollable: true,
                items: [
                    {
                        xtype: 'container',
                        id: 'multimidtitle',
                        padding: '15 0 0 15',
                        items: [
                            {
                                xtype: 'container',
                                html: '<h4><div class="x-form-fieldset-title x-docked-top" id="list-title"><div class="x-innerhtml " id="list-title-inner"> Text123 </div></div></h4>',
                                id: 'multimidtitleid'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        id: 'multimidlistid',
                        ui: 'round',
                        scrollable: false,
                        itemTpl: [
                            '{value}'
                        ],
                        store: 'midstoreid',
                        disableSelection: false
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'multilistview',
                layout: {
                    type: 'card'
                },
                scrollable: false,
                items: [
                    {
                        xtype: 'container',
                        id: 'multiid',
                        layout: {
                            type: 'vbox'
                        },
                        scrollable: true,
                        items: [
                            {
                                xtype: 'container',
                                docked: 'top',
                                height: 35,
                                hidden: true,
                                id: 'multilistparentid',
                                margin: 3,
                                layout: {
                                    pack: 'end',
                                    type: 'hbox'
                                },
                                scrollable: false
                            },
                            {
                                xtype: 'container',
                                id: 'multilisttitle',
                                padding: '15 0 0 15',
                                items: [
                                    {
                                        xtype: 'container',
                                        html: '<h4><div class="x-form-fieldset-title x-docked-top" id="list-title"><div class="x-innerhtml " id="list-title-inner"> Text123 </div></div></h4>',
                                        id: 'multilisttitleid'
                                    }
                                ]
                            },
                            {
                                xtype: 'list',
                                id: 'multilistid',
                                ui: 'round',
                                scrollable: false,
                                itemTpl: [
                                    '{value}'
                                ],
                                store: 'datastoreid',
                                allowDeselect: true,
                                disableSelection: false,
                                mode: 'MULTI'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        id: 'multiotherid',
                        margin: '10 0 0 0',
                        padding: '0 10 0 10',
                        layout: {
                            type: 'vbox'
                        },
                        scrollable: 'vertical',
                        items: [
                            {
                                xtype: 'container',
                                html: '<h4><div class="x-form-fieldset-title x-docked-top" id="list-title"><div class="x-innerhtml " id="list-title-inner"> Text123 </div></div></h4>',
                                id: 'multiothertitleid',
                                margin: 5
                            },
                            {
                                xtype: 'fieldset',
                                id: 'multiotherfieldsetid',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: [
                                            'search-field-clear-size'
                                        ],
                                        id: 'multiotherfieldid',
                                        placeHolder: 'Enter text here.'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                id: 'multiotherbuttonid',
                                ui: 'main-button',
                                text: 'Add'
                            },
                            {
                                xtype: 'list',
                                cls: [
                                    'removable-item'
                                ],
                                id: 'multiotherlistid',
                                style: '"{background:#FFFFFF}"',
                                ui: 'round',
                                scrollable: false,
                                itemTpl: [
                                    '{value}'
                                ],
                                store: 'otherstoreid',
                                onItemDisclosure: true
                            }
                        ]
                    }
                ]
            }
        ]
    }

});