/*
 * File: app/view/SingleView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Incident.view.SingleView', {
    extend: 'Ext.Container',
    alias: 'widget.singleview',

    requires: [
        'Ext.field.Search',
        'Ext.dataview.List'
    ],

    config: {
        id: 'singleviewid',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                id: 'singletoolbarid',
                items: [
                    {
                        xtype: 'button',
                        id: 'singlebackbuttonid',
                        width: 125,
                        text: 'Back'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'singleclearbuttonid',
                        ui: 'decline',
                        width: 125,
                        text: 'Clear'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                id: 'singlesearchbarid',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        cls: [
                            'search-field-clear-size'
                        ],
                        id: 'singlesearchfieldid',
                        maxWidth: 600,
                        width: '90%',
                        placeHolder: 'Search...'
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'singlemidview',
                layout: {
                    type: 'vbox'
                },
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'container',
                        id: 'singlemidtitle',
                        padding: '15 0 0 15',
                        items: [
                            {
                                xtype: 'container',
                                html: '<h4><div class="x-form-fieldset-title x-docked-top" id="list-title"><div class="x-innerhtml " id="list-title-inner"> Text123 </div></div></h4>',
                                id: 'singlemidtitleid'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        id: 'singlemidlistid',
                        ui: 'round',
                        scrollable: false,
                        itemTpl: [
                            '{value}'
                        ],
                        store: 'midstoreid',
                        disableSelection: true
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'singlelistview',
                layout: {
                    type: 'card'
                },
                scrollable: false,
                items: [
                    {
                        xtype: 'container',
                        id: 'singleid',
                        ui: '',
                        layout: {
                            type: 'vbox'
                        },
                        scrollable: 'vertical',
                        items: [
                            {
                                xtype: 'container',
                                id: 'singlelisttitle',
                                padding: '15 0 0 15',
                                items: [
                                    {
                                        xtype: 'container',
                                        html: '<h4><div class="x-form-fieldset-title x-docked-top" id="list-title"><div class="x-innerhtml " id="list-title-inner"> Text123 </div></div></h4>',
                                        id: 'singlelisttitleid'
                                    }
                                ]
                            },
                            {
                                xtype: 'list',
                                id: 'singlelistid',
                                ui: 'round',
                                scrollable: false,
                                itemTpl: [
                                    '{value}'
                                ],
                                store: 'datastoreid'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        id: 'singleotherid',
                        margin: '10 0 0 0',
                        padding: '0 10 0 10',
                        ui: '',
                        scrollable: 'vertical',
                        items: [
                            {
                                xtype: 'container',
                                html: '<h4><div class="x-form-fieldset-title x-docked-top" id="list-title"><div class="x-innerhtml " id="list-title-inner"> Text123 </div></div></h4>',
                                id: 'singleothertitleid',
                                margin: 5
                            },
                            {
                                xtype: 'fieldset',
                                id: 'singleotherfieldsetid',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        ui: 'text',
                                        id: 'singleotherfieldid',
                                        labelAlign: 'right',
                                        labelCls: 'label-style-fix'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                id: 'singleotherbuttonid',
                                ui: 'main-button',
                                text: 'Add'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});