/*
 * File: app/view/ThankYouView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Incident.view.ThankYouView', {
    extend: 'Ext.Container',
    alias: 'widget.thankyouview',

    config: {
        id: 'thankyouviewid',
        layout: {
            align: 'center',
            type: 'vbox'
        },
        scrollable: true,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                id: 'thankyoutitleid',
                title: 'Thank you'
            },
            {
                xtype: 'container',
                id: 'thankyouhtmlid',
                padding: 10,
                width: '100%'
            },
            {
                xtype: 'container',
                height: 30
            },
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'button',
                        height: 35,
                        id: 'newreportbuttonid',
                        ui: 'confirm',
                        text: 'Create Another Report?'
                    }
                ]
            }
        ]
    }

});