/*
 * File: app/model/FieldData.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Incident.model.FieldData', {
    extend: 'Ext.data.Model',
    alias: 'model.fielddata',

    config: {
        idProperty: 'uniqueId',
        identifier: {
            type: 'uuid'
        },
        fields: [
            {
                name: 'id'
            },
            {
                name: 'type'
            },
            {
                name: 'value'
            },
            {
                name: 'parent_id'
            },
            {
                name: 'parent_value'
            },
            {
                convert: function(v, rec) {
                    if(rec.data.type)
                    return String(rec.data.id) + '_' + String(rec.data.type);
                    else
                    return rec.data.id;
                },
                name: 'uniqueId'
            }
        ]
    }
});