/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    name: 'Incident',
    requires: [
        'Ext.data.identifier.Uuid',
        'Ext.data.proxy.SessionStorage'
    ],
    models: [
        'TemplateModel',
        'LocalModel',
        'FieldData',
        'AuxConfig',
        'TabModel',
        'ConfigModel'
    ],
    stores: [
        'TemplateStore',
        'AuxStore',
        'GlobalStore',
        'SettingsStore',
        'StaticStore',
        'TabStore',
        'ConfigStore',
        'DataStore',
        'MidStore',
        'TempStore',
        'OtherStore'
    ],
    views: [
        'LoginView',
        'Homescreen',
        'SettingsView',
        'Mainview',
        'Canvas',
        'SingleView',
        'MultiView',
        'ThankYouView'
    ],
	
    controllers: [
        'LogInControl',
        'GlobalControl',
        'TemplateControl',
        'FieldsControl'
    ],

    launch: function() {

        Ext.create('Incident.view.LoginView', {fullscreen: true});
    }

});
